"""add_duration_and_video_url_to_lessons

Revision ID: 08cea36964bf
Revises: c9d2ca27115c
Create Date: 2025-07-05 00:55:32.850578

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '08cea36964bf'
down_revision: Union[str, None] = 'c9d2ca27115c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lessons', sa.Column('duration', sa.Integer(), nullable=True))
    op.add_column('lessons', sa.Column('video_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lessons', 'video_url')
    op.drop_column('lessons', 'duration')
    # ### end Alembic commands ###
