"""Add_enrollment_count_to_courses

Revision ID: 4bd4f572bc7f
Revises: 75dfc8f24b7a
Create Date: 2025-06-28 04:29:13.504842

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4bd4f572bc7f'
down_revision: Union[str, None] = '75dfc8f24b7a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add column with default value first
    op.add_column('courses', sa.Column('enrollment_count', sa.Integer(), nullable=True, server_default='0'))
    # Update existing records to have default value
    op.execute("UPDATE courses SET enrollment_count = 0 WHERE enrollment_count IS NULL")
    # Make column NOT NULL
    op.alter_column('courses', 'enrollment_count', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('courses', 'enrollment_count')
    # ### end Alembic commands ###
