"""Add Google OAuth support to users table

Revision ID: 76a0fbe88b14
Revises: 4bd4f572bc7f
Create Date: 2025-07-04 22:20:24.151972

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '76a0fbe88b14'
down_revision: Union[str, None] = '4bd4f572bc7f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('google_id', sa.String(length=255), nullable=True))
    # Add auth_provider column as nullable first
    op.add_column('users', sa.Column('auth_provider', sa.String(length=50), nullable=True))
    # Update existing users to have 'local' as auth_provider
    op.execute("UPDATE users SET auth_provider = 'local' WHERE auth_provider IS NULL")
    # Now make auth_provider NOT NULL
    op.alter_column('users', 'auth_provider', nullable=False)
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.create_index(op.f('ix_users_google_id'), 'users', ['google_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_google_id'), table_name='users')
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.drop_column('users', 'auth_provider')
    op.drop_column('users', 'google_id')
    # ### end Alembic commands ###
