"""update_lesson_schema_fields

Revision ID: c9d2ca27115c
Revises: 76a0fbe88b14
Create Date: 2025-07-05 00:49:40.171071

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c9d2ca27115c'
down_revision: Union[str, None] = '76a0fbe88b14'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
